# Generated by Django 3.0.2 on 2020-01-12 14:06

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_inputtexts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtexts',
            name='input_txts',
            field=models.FileField(storage=web.models.OverwriteStorage(), upload_to='input_txts'),
        ),
        migrations.AlterField(
            model_name='wordlists',
            name='word_lists',
            field=models.FileField(max_length=10, storage=web.models.OverwriteStorage(), upload_to='word_lists/'),
        ),
    ]
