# Generated by Django 3.0.3 on 2020-02-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtexts',
            name='input_txts',
            field=models.FileField(upload_to='input_txts/'),
        ),
    ]
