INPUT_TXTS_DIR_NAME = "input_txts"
OUTPUT_TXTS_DIR_NAME = "output_txts"
WORD_LISTS_TXTS_DIR_NAME = "word_lists"
WORD_LISTS_FILE_NAME = "word_lists.xlsx"
USER_GROUP_WRITERS = "writers"
USER_GROUP_LEVELERS = "levelers"
