# Generated by Django 3.0.2 on 2020-01-12 14:07

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200112_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlists',
            name='word_lists',
            field=models.FileField(max_length=15, storage=web.models.OverwriteStorage(), upload_to='word_lists/'),
        ),
    ]
